### ISSUE TITLE
suggestion to make inp_data const

### ISSUE THREAD

**Issue by itlods** [jpcima/zita-resampler#2]
In all three header files inp_data could be declared const like

const float *inp_data;

this will make it more in line with other libs, and make it more smooth to pass a const pointer to the resampler. I think this will be fully backward compatible.

Similar I would have liked inp_count and out_count to be std::size_t. This however is not fully backward compatible, so it is probably a non-starter?

**Comment by jpcima** [comment]
>Similar I would have liked inp_count and out_count to be std::size_t. This however is not fully backward compatible, so it is probably a non-starter?

I can't imagine any situation where this may be a problem.
I would rather conserve compatibility with upstream Zita by Fons Adriaensen.

>this will make it more in line with other libs, and make it more smooth to pass a const pointer to the resampler. I think this will be fully backward compatible.

This sounds reasonable.
